string:
    lift: LIFT
    down:
        lift: LIFT DOWN
    normal:
        open: '['
        close: ']'
    private:
        open: '{'
        close: '}'
    up:
        lift: LIFT UP
check:
    destination:
        paranoid: true
