string:
    lift: LIFT
    down:
        lift: LIFT DOWN
    normal:
        open: '['
        close: ']'
    private:
        open: '{'
        close: '}'
    up:
        lift: LIFT UP
check:
    destination:
        paranoid: true
upm: true
upm_update: http://www.pvp.mcs.square7.ch/improvedsignlifts.json
upm_configtype:
    string:
        lift: string
        down:
            lift: string
        normal:
            open: string
            close: string
        private:
            open: string
            close: string
        up:
            lift: string
    check:
        destination:
            paranoid: boolean