name: ImprovedSignLift
main: com.minecraftserver.improvedsignlifts.ImprovedSignLift
website: http://www.minecraftserver.com/
version: 1.09
author: M0P, AquaXV
commands:
    sl:
    
permissions:
    signlift.user.*:
        description: Gives access to all SignLift privileges
        children:
            signlift.user.create.*: true
            signlift.user.modify.private.member: true
            signlift.user.use.normal: true
            signlift.user.use.private.own: true
            signlift.user.use.private.other: true 
    signlift.user.create.*:
        description: Gives access to all SignLift create privileges
        children:
            signlift.user.create.normal: true
            signlift.user.create.private.own: true
    signlift.user.create.normal:
        description: Permits the creation of a normal sign lifts for anyone to use
        default: true
    signlift.user.create.private.own:
        description: Permits the creation of private sign lifts with the PRIVATE tag
        default: true
    signlift.user.modify.private.member:
        description: Permits the modification of private sign lifts (adding/removing member)
        default: true
    signlift.user.use.normal:
        description: Permits the use of any normal sign lift
        default: true
    signlift.user.use.private.own:
        description: Permits the use of any private sign lift made for this user
        default: true
    signlift.user.use.private.other:
        description: Permits the use of any private sign lift where player is member
        default: true
    signlift.admin:
        description: Permits the use/creation/destruction of any sign lift
        default: op