name: ImprovedSignLift
main: com.minecraftserver.improvedsignlift.ImprovedSignLift
website: http://minecraftserver.com/
version: 1.00
permissions:
    signlift.*:
        description: Gives access to all SignLift privileges
        children:
            signlift.create.*: true
            signlift.use.normal: true
            signlift.use.private.own: true
            signlift.use.private.other: true 
    signlift.create.*:
        description: Gives access to all SignLift create privileges
        children:
            signlift.create.normal: true
            signlift.create.private.own: true
            signlift.create.private.other: true
    signlift.create.normal:
        description: Permits the creation of a normal sign lifts for anyone to use
        default: true
    signlift.create.private.own:
        description: Permits the creation of private sign lifts with the PRIVATE tag
        default: true
    signlift.modify.private.member:
        description: Permits the modification of private sign lifts (adding/removing member)
        default: true
    signlift.use.normal:
        description: Permits the use of any normal sign lift
        default: true
    signlift.use.private.own:
        description: Permits the use of any private sign lift made for this user
        default: true
    signlift.use.private.others:
        description: Permits the use of any private sign lift where player is member
        default: op